export const TEST_SERVICE = 'TEST-SERVICE';
export const PROFILE_SERVICE = 'PROFILE-SERVICE';
export const ERROR_MIDDLEWARE = 'ERROR-MIDDLEWARE';

export const UNAUTHORIZED = 'UNAUTHORIZED';
export const FORBIDDEN = 'FORBIDDEN';
