export const TEST_SERVICE = 'TEST-SERVICE';
export const CV_PRESIGN_SERVICE = 'CV-PRESIGN-SERVICE';
export const ERROR_MIDDLEWARE = 'ERROR-MIDDLEWARE';

export const UNAUTHORIZED = 'UNAUTHORIZED';
export const FORBIDDEN = 'FORBIDDEN';
